packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@supabase/server@1.2.0'

packageExtensions:
  '@carlos-pinto/contracts@*':
    dependencies:
      zod: 4.4.3
  '@carlos-pinto/config@*':
    dependencies:
      zod: 4.4.3
